name: codexapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  highlight: ^0.7.0
  flutter_highlighting: ^0.9.0+11.8.0
  blurrycontainer: ^1.0.2
  flutter_native_splash: ^2.2.19
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - images/java-14-logo.png
   - images/Dart-logo.png
   - images/Python-logo.png
   - images/js-logo.png
   - images/react-logo.png
   - images/flutter-logo.png
   - images/spring-logo.png
   - images/hibernate-logo.png
   - images/maria.png
   - images/mongodb.png
   - images/mysql.png
   - images/oracle.png
   - images/git-img.png
   - images/github.png
   - images/postman.png
   - images/vs-logo.png
   - images/bg1.jpeg
   - images/bg2.jpeg
   - images/bg3.jpeg
   - images/bg4.webp
   - images/bg5.jpeg
   - images/bg6.jpeg
   - images/bg7.jpg
   - images/bg8.jpeg
   - images/applogo1.png
   - images/applogo2.png
   - images/apple.png
   - images/google.png


