List JavaTopics = [
    "Introduction to java",
    "First step towards java",
    "Naming convensions",
    "Commenting",
    "Datatypes",
    "Operators",
    "Control statements",
    "Input output",
    "Array",
    "Commandline arguments",
    "String",
    "Introduction to oop",
    "Constructor",
    "Polymorfism",
    "Abstraction",
    "Interface",
    "Colloctions"
    "Multi-Threads",
    "Packages",
  ];
  
  List DartTopics = [
    "Introduction to Dart",
    "First step towards Dart",
    "Naming convensions",
    "Commenting",
    "Datatypes",
    "Operators",
    "Control statements",
    "Input output",
    "Array",
    "Commandline arguments",
    "String",
    "Introduction to oop",
    "Constructor",
    "Polymorfism",
  ];